// Auto-generated by scripts/import2024.py — do not edit by hand
// 2024 season constants

export const PAR  = [4,3,4,5,4,3,4,5,4];
export const SI   = [1,3,7,8,4,9,2,6,5];

export const RAINOUT_SUB = {
  6: 0, 7: 1, 8: 2,
};

export const TEAMS = {
  1: {name:"Brosius - Albano", p1:"Steve Brosius", p2:"Mike Albano"},
  2: {name:"Saenz - Huston", p1:"Bob Saenz", p2:"Dennis Huston"},
  3: {name:"Carickhoff - Sanson", p1:"Jack Carickhoff", p2:"Henry Sanson"},
  4: {name:"Celenza - Shute", p1:"Mike Celenza", p2:"Rod Shute"},
  5: {name:"Charles - Dagg", p1:"Brian Charles", p2:"Karl Dagg"},
  6: {name:"Deshaies - Glascott", p1:"Jacob Deshaies", p2:"Scott Glascott"},
  7: {name:"Mistry - Reddy", p1:"Baz Mistry", p2:"Sanjay Reddy"},
  8: {name:"Coyne - Franks", p1:"Chris Coyne", p2:"John Franks"},
  9: {name:"Mulvey - Torak", p1:"Tom Mulvey", p2:"Kevin Torak"},
  10: {name:"Wagner - Hammond", p1:"Betsy Wagner", p2:"Gordon Hammond"},
  11: {name:"Wzorek - Fahey", p1:"Barry Wzorek", p2:"Chris Fahey"},
  12: {name:"Lorenz - Huckestein", p1:"Gabe Lorenz", p2:"Jake Huckestein"},
  13: {name:"West - Herman", p1:"Jack West", p2:"Ron Herman"},
  14: {name:"Pineno - MacKenzie", p1:"Scot Pineno", p2:"Scott MacKenzie"},
  15: {name:"Posey - Miller", p1:"Russ Posey", p2:"Jon Miller"},
  16: {name:"Lukas - Blizard", p1:"Rhonda Lukas", p2:"Carol Blizard"},
  17: {name:"Milligan - Pavelik", p1:"Pat Milligan", p2:"Barry Pavelik"},
  18: {name:"Harvey - Rowles", p1:"John Harvey", p2:"Jeff Rowles"}
};

export const ALL_PLAYERS = Object.entries(TEAMS).flatMap(([tid, t]) => [
  {tid: parseInt(tid), pi: 0, name: t.p1, team: t.name},
  {tid: parseInt(tid), pi: 1, name: t.p2, team: t.name},
]);

// Week 1 handicaps (from 2024 Summary sheet)
// Note: hcpOverrides in Firebase store the exact weekly values — these are
// just used as the startHcp reference for new-member detection.
export const DEFAULT_HCP = {
  1: [4,9],
  2: [7,9],
  3: [0,4],
  4: [13,10],
  5: [4,3],
  6: [2,12],
  7: [6,7],
  8: [14,7],
  9: [7,4],
  10: [20,11],
  11: [8,7],
  12: [14,10],
  13: [13,16],
  14: [10,8],
  15: [10,16],
  16: [9,27],
  17: [19,20],
  18: [8,11]
};

// New members in 2024: Gabe Lorenz (12,0), Jake Huckestein (12,1), Kevin Torak (9,1), Mike Celenza (4,0)
export const NEW_MEMBERS = [[12, 0], [12, 1], [9, 1], [4, 0]];

export function isNewMember(tid, pi) {
  return NEW_MEMBERS.some(([t, p]) => t === tid && p === pi);
}

export const HCP_PCT = {1:0.65, 2:0.70, 3:0.75, 4:0.80};
export const HCP_CAP = null; // no cap for 2024
export const HCP_ROUNDS = null; // average ALL rounds (not best 7) for 2024
export const NEW_MEMBER_HCP_PCT = 0.60; // 2024 new member rate
export const PLAYOFF_START_WEEK = 19; // all 18 teams play week 18 as regular schedule

// Schedule derived from the Excel — dates are blank (fill in if needed)
export const SCHEDULE_RAW = [
  [1, null, [13,17],[14,15],[3,6],[1,5],[2,4],[10,11],[7,12],[8,9],[16,18]],
  [2, null, [14,18],[13,16],[4,5],[2,6],[1,3],[9,12],[8,11],[7,10],[15,17]],
  [3, null, [8,10],[6,12],[7,9],[13,15],[11,18],[14,16],[2,3],[5,17],[1,4]],
  [4, null, [3,9],[5,11],[1,14],[4,16],[6,17],[8,13],[10,15],[12,18],[2,7]],
  [5, null, [2,11],[3,7],[6,16],[1,17],[4,14],[10,18],[12,13],[8,15],[5,9]],
  [6, null, [4,6],[10,12],[7,13],[9,11],[15,18],[2,14],[16,17],[3,5],[1,8]],
  [7, null, [11,14],[7,16],[3,12],[5,8],[2,10],[4,18],[6,13],[1,15],[9,17]],
  [8, null, [5,7],[2,9],[4,17],[6,14],[1,16],[12,15],[8,18],[10,13],[3,11]],
  [9, null, [7,17],[9,14],[5,10],[2,12],[3,8],[6,15],[1,18],[4,13],[11,16]],
  [10, null, [4,10],[1,6],[13,18],[9,15],[7,11],[2,5],[3,16],[14,17],[8,12]],
  [11, null, [9,16],[11,17],[2,8],[3,10],[5,12],[1,13],[4,15],[6,18],[7,14]],
  [12, null, [3,13],[5,15],[8,14],[10,16],[12,17],[1,9],[4,11],[6,7],[2,18]],
  [13, null, [5,18],[2,13],[12,16],[8,17],[10,14],[4,7],[6,9],[1,11],[3,15]],
  [14, null, [2,15],[3,18],[10,17],[12,14],[8,16],[6,11],[1,7],[4,9],[5,13]],
  [15, null, [1,12],[4,8],[11,15],[7,18],[9,13],[3,17],[5,14],[2,16],[6,10]],
  [16, null, [6,8],[1,10],[9,18],[11,13],[7,15],[5,16],[2,17],[3,14],[4,12]],
  [17, null, [15,16],[17,18],[1,2],[3,4],[5,6],[7,8],[9,10],[11,12],[13,14]],
  [18, null, [3,7],[9,11],[14,18],[2,6],[1,5],[12,13],[4,10],[8,16],[15,17]]
];

export const BASE_TEE_TIMES = [
  "4:10 PM","4:20 PM","4:30 PM","4:40 PM","4:50 PM",
  "5:00 PM","5:10 PM","5:20 PM","5:30 PM",
];
export const TEE_TIME_OVERRIDES = {};

export function buildSchedule() {
  const s = {};
  for (const [week, date, ...pairs] of SCHEDULE_RAW) {
    s[week] = {week, date, pairs: (pairs || []).filter(p => Array.isArray(p))};
  }
  return s;
}

export const SCHEDULE = buildSchedule();

export function getTeeTimes(week) {
  return TEE_TIME_OVERRIDES[week] || BASE_TEE_TIMES;
}
