// Auto-generated by scripts/import2025.py — do not edit by hand
// 2025 season constants

export const PAR  = [4,3,4,5,4,3,4,5,4];
export const SI   = [1,3,7,8,4,9,2,6,5];

export const RAINOUT_SUB = {
  6: 0, 7: 3, 8: 2,
};

export const TEAMS = {
  1: {name:"Charles - Dagg", p1:"Brian Charles", p2:"Karl Dagg"},
  2: {name:"Brosius - Albano", p1:"Steve Brosius", p2:"Mike Albano"},
  3: {name:"Mistry - Reddy", p1:"Baz Mistry", p2:"Sanjay Reddy"},
  4: {name:"Pineno - MacKenzie", p1:"Scot Pineno", p2:"Scott MacKenzie"},
  5: {name:"Carickhoff - Celenza", p1:"Jack Carickhoff", p2:"Mike Celenza"},
  6: {name:"Deshaies - Glascott", p1:"Jacob Deshaies", p2:"Scott Glascott"},
  7: {name:"Harvey - Rowles", p1:"John Harvey", p2:"Jeff Rowles"},
  8: {name:"Saenz - Huston", p1:"Bob Saenz", p2:"Dennis Huston"},
  9: {name:"Fahey - Olivos", p1:"Chris Fahey", p2:"JC Olivos"},
  10: {name:"Mulvey - Nelson", p1:"Tom Mulvey", p2:"Chris Nelson"},
  11: {name:"West - Herman", p1:"Jack West", p2:"Ron Herman"},
  12: {name:"Lorenz - Huckestein", p1:"Gabe Lorenz", p2:"Jake Huckestein"},
  13: {name:"Wagner - Hammond", p1:"Betsy Wagner", p2:"Gordon Hammond"},
  14: {name:"Franks - Lightbody", p1:"John Franks", p2:"Scott Lightbody"},
  15: {name:"Jurden - Schantz", p1:"Jesse Jurden", p2:"Tracy Schantz"},
  16: {name:"Lukas - Blizard", p1:"Rhonda Lukas", p2:"Carol Blizard"},
  17: {name:"Posey - Minasian", p1:"Russ Posey", p2:"Aret Minasian"},
  18: {name:"Pavelik - Mitchell", p1:"Barry Pavelik", p2:"Mark Mitchell"}
};

export const ALL_PLAYERS = Object.entries(TEAMS).flatMap(([tid, t]) => [
  {tid: parseInt(tid), pi: 0, name: t.p1, team: t.name},
  {tid: parseInt(tid), pi: 1, name: t.p2, team: t.name},
]);

export const DEFAULT_HCP = {
  1: [6,5],
  2: [7,8],
  3: [6,7],
  4: [9,10],
  5: [2,10],
  6: [1,12],
  7: [9,11],
  8: [7,11],
  9: [6,7],
  10: [8,7],
  11: [12,15],
  12: [11,3],
  13: [16,12],
  14: [9,1],
  15: [14,11],
  16: [9,31],
  17: [10,9],
  18: [19,14]
};

export const NEW_MEMBERS = {};

export const HCP_PCT = [0, 0.90, 0.90, 0.90, 0.90];
export const HCP_CAP = 2;
export const HCP_ROUNDS = 7;
export const NEW_MEMBER_HCP_PCT = 0.65;
export const PLAYOFF_START_WEEK = 18;

export const SCHEDULE_RAW = [
  [1, null, [13,17],[14,15],[3,6],[8,9],[2,4],[10,11],[7,12],[1,5],[16,18]],
  [2, null, [14,18],[13,16],[4,5],[2,6],[1,3],[9,12],[8,11],[7,10],[15,17]],
  [3, null, [8,10],[6,12],[7,9],[13,15],[11,18],[14,16],[2,3],[5,17],[1,4]],
  [4, null, [3,9],[5,11],[1,14],[4,16],[6,17],[8,13],[10,15],[12,18],[2,7]],
  [5, null, [2,11],[3,7],[6,16],[5,9],[4,14],[10,18],[12,13],[8,15],[1,17]],
  [6, null, [4,6],[10,12],[7,13],[9,11],[15,18],[2,14],[16,17],[3,5],[1,8]],
  [7, null, [11,14],[7,16],[3,12],[5,8],[2,10],[4,18],[6,13],[1,15],[9,17]],
  [8, null, [5,7],[2,9],[4,17],[6,14],[1,16],[12,15],[8,18],[10,13],[3,11]],
  [9, null, [7,17],[9,14],[5,10],[2,12],[3,8],[6,15],[1,18],[4,13],[11,16]],
  [10, null, [4,10],[1,6],[13,18],[9,15],[7,11],[2,5],[3,16],[14,17],[8,12]],
  [11, null, [9,16],[11,17],[2,8],[3,10],[5,12],[7,14],[4,15],[6,18],[1,13]],
  [12, null, [3,13],[5,15],[8,14],[10,16],[4,11],[2,18],[12,17],[6,7],[1,9]],
  [13, null, [5,18],[2,13],[12,16],[8,17],[10,14],[1,11],[6,9],[4,7],[3,15]],
  [14, null, [2,15],[3,18],[10,17],[12,14],[8,16],[6,11],[4,9],[1,7],[5,13]],
  [15, null, [1,12],[4,8],[11,15],[7,18],[9,13],[3,17],[5,14],[2,16],[6,10]],
  [16, null, [6,8],[3,14],[9,18],[11,13],[7,15],[5,16],[2,17],[1,10],[4,12]],
  [17, null, [15,16],[17,18],[1,2],[3,4],[5,6],[7,8],[9,10],[11,12],[13,14]],
  [18, null, [1,3],[10,14],[2,4],[11,16],[8,12],[6,7],[13,18],[9,17],[5,15]]
];

export const BASE_TEE_TIMES = [
  "4:10 PM","4:20 PM","4:30 PM","4:40 PM","4:50 PM",
  "5:00 PM","5:10 PM","5:20 PM","5:30 PM",
];
export const TEE_TIME_OVERRIDES = {};

export function buildSchedule() {
  const s = {};
  for (const [week, date, ...pairs] of SCHEDULE_RAW) {
    s[week] = {week, date, pairs: (pairs || []).filter(p => Array.isArray(p))};
  }
  return s;
}

export const SCHEDULE = buildSchedule();

export function getTeeTimes(week) {
  return TEE_TIME_OVERRIDES[week] || BASE_TEE_TIMES;
}

export function isNewMember(tid, pi) {
  return !!NEW_MEMBERS[`${tid}-${pi}`];
}
